### ISSUE TITLE
[bug] Options.TimeLive 跟极光文档不一致

### ISSUE THREAD

**Issue by Gofi123** [zwczou/jpush#1]
![default](https://user-images.githubusercontent.com/34090548/39510627-ece17cc4-4e1c-11e8-909c-30d1d45383a3.png)

Options.TimeLive 设置为 0 时， 生成的json是会忽略 TimeLive 这项的

https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/#options
![default](https://user-images.githubusercontent.com/34090548/39510680-1c97fdc6-4e1d-11e8-9c33-01a7f4162a4f.png)

跟极光文档里的 默认86400，设置为0时表示不保留离线消息 不一致

**Comment by zwczou** [comment]
额，如果去掉omitempty的话，那默认为0，就是不保留离线消息了...
