### ISSUE TITLE
...string

### ISSUE THREAD

**Issue by zlgale** [zwczou/jpush#3]
SetTag怎么传值
`var audience jpush.Audience
var strTag2 =  []string{"深圳","北京"}
audience.SetTag(strTag2...)`

**Comment by zwczou** [comment]
你这用法很对呀，
只不过初始化的时候，不能这样，因为map没有被初始化
```go
audience := NewAudience()
```
也可用直接 
```go
audience.SetTag(strTag2...)
audience.SetTag("深圳","北京")
```
