### ISSUE TITLE
devices相关接口域名改成device.jpush.cn了

### ISSUE THREAD

**Issue by louzhu123** [zwczou/jpush#8]

**Comment by zwczou** [comment]
刚刚去看了下，确实更换地址了

[文档](https://docs.jiguang.cn/jpush/server/push/rest_api_v3_device/)

**Comment by zwczou** [comment]
已经支持了，但是我现在没有测试环境了，你可以测试下

**Comment by louzhu123** [comment]
> 已经支持了，但是我现在没有测试环境了，你可以测试下

嗯嗯，试了下，可以
